PINE_CONE_INDEX_NAME = "langchain-demo"
PINECONE_API_KEY = 'PINECONE_API_KEY'
PINECONE_ENVIRONMENT = "PINECONE_ENVIRONMENT"
OPENAI_API_KEY = "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"
VECTOR_QUERY_NAME_SPACE = "pdf-first-version"
GPT_MODEL_TYPE = "gpt-3.5-turbo"
TEST_CONSTANT = "TEST_CONSTANT"